baseURL: "https://www.compagniebarbarie.be/"
DefaultContentLanguage: nl
defaultContentLanguageInSubdir: true
languageCode: "be-nl"
title: Compagnie Barbarie
languages:
  nl:
    title: Compagnie Barbarie
  en:
    title: Company Barbarie
