baseURL: "https://www.compagniebarbarie.be/"
DefaultContentLanguage: nl
languageCode: "be-nl"
title: Compagnie Barbarie
languages:
  nl:
    title: Compagnie Barbarie
    menu:
      main:
        - name: Voorstellingen
          url: /#shows
        - name: Over Ons
          url: /over-ons/
        - name: Pers
          url: /pers/

  en:
    title: Compagnie Barbarie
    menu:
      main:
        - name: Shows
          url: /#shows
        - name: About Us
          url: /about/
        - name: Media
          url: /media/
